services:
  db:
    image: postgres:15
    container_name: db-petcare
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petcare_admin -d petcare_prod"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.prod
    # volumes:
    # moved to Dockerfile
    #   - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

  petcare:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5002:5000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.prod


