services:
  app:
    build: .
    ports: 
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgresf
      DATABASE_NAME: petcare
      # JWT_SECRET
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postegres
      POSTGRES_PASSWORD: postgresf
      POSTGRES_DB: petcare
    ports:
    - "5432:5432"

