services:
  db:
    image: postgres:15
    container_name: db-petcare
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petcare_admin -d petcare_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: petcare_admin
      POSTGRES_PASSWORD: petcare_admin
      POSTGRES_DB: petcare_db

  petcare:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "5002:5002"
    depends_on:
      db:
        condition: service_healthy
    environment:    
      PORT: 5002
      NODE_ENV: production
      JWT_SECRET: "$$2y$12$hYrxrRlOFt3lGAPg2v5LnOupdSlDKict7Wy.1awUB6KVKQfbt4fjG"
   


